### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by rs028**
Self explanatory. I have added and all the places where comments and descriptions are missing (`???`), renamed a few of the secondary modules to have a consistent naming style (`modulename_mod`) and tried to simplify a few declarations. As usual, I am open to suggestions :)

PS: you can merge straight away if you are happy with this. I am not going to do more until Friday.

### CODE REVIEW

**Comment by spco** [comment]
Great! Is this ready for review? (Though I won't get to it today, sorry)

**Comment by spco** [comment]
Just rebased, then I'll check it's all ok to merge.

**Comment by spco** [comment]
I've reverted just a couple of bits - specifically, it's probably better to lay out `intent(in/out)` variable declarations in the order they are in the function call, rather than clumping them together. I'll merge this when the test finishes. I'll go back myself and update the empty comments as appropriate.

**Comment by rs028** [comment]
Okay :+1:

**Pull request merged**
