### PR TITLE
Reorganize

### PR DESCRIPTION
**Pull request by rs028**
I have moved the subroutines in modelConfiguration/extraOutputSubroutines.f90 to outputFunctions.f90 and utilityFunctions.f90
The files temperature.f90 and zenith.f90 have been merged with utilityFunctions.f90. The Makefile has been updated accordingly but there is a reference to extraOutputSubroutines.f90 in tools/facsimileToFortranMechanismConverter.py that has to be dealt with (although that script does not exist anymore).

### CODE REVIEW

**Comment by spco** [comment]
Great! If you're able to fix these merge conflicts, and then submit that as another commit (just push while on this branch again, and it will automatically come up on this PR too) that would be great - otherwise I'll do that when I have better internet again.

**Comment by rs028** [comment]
Okay, will do. should I delete yesterday's pull request?

**Comment by spco** [comment]
If you'd also like to change the reference in tools/facsimileToFortranMechanismConverter.py (now tools/mech_converter.py) as another commit to this PR then that would be great. It's probably best to close yesterday's PR, as any changes you now make to your master branch, and then push to origin, would be reflected in that (including just keeping up with the upstream repository).

**Comment by rs028** [comment]
Okay. I am having trouble updating  my fork. As per your instructions yesterday I did:

git pull upstream master

which worked 

git push origin master

**Comment by rs028** [comment]
Cancel  PR. See PR #38.

**Comment by rs028** [comment]
Sorry. I am making a mess here :(
Shoul be okay now.

**Comment by spco** [comment]
Do you mean "another git push" as in, after the git pull upstream master, you did git push origin master but that gave you conflicts?

**Comment by rs028** [comment]
git push origin master

I was trying to sync the upstream repo, my local repo and my github fork

**Comment by spco** [comment]
If so, please do the following: making sure you are on master branch:
git log --oneline
this will show you the history of commits on the master branch. What is the top commit message or hash?

**Comment by rs028** [comment]
The top entry is: 
b32c2df Add osx as os option to .travis.yml.

If I do git checkout master. I get the error message
Makefile: needs merge
error: you need to resolve your current index first
so I guess I need to fix that first and try again

**Comment by spco** [comment]
So you are not on the master branch?
git branch
will show you which branch you are on, or
git status

**Comment by rs028** [comment]
I am on master. git status returns:

# On branch master
# Your branch and 'origin/master' have diverged,
# and have 9 and 3 different commits each, respectively.
#   (use "git pull" to merge the remote branch into yours)
#
# You have unmerged paths.
#   (fix conflicts and run "git commit")
#
# Changes to be committed:
#
#	modified:   atchem.f90
#	renamed:    modelConfigFunctions.f90 -> configFunctions.f90
#	deleted:    modelConfiguration/extraOutputSubroutines.f90
#	modified:   outputFunctions.f90
#	deleted:    temperature.f90
#	renamed:    zenith.f90 -> utilityFunctions.f90
#
# Unmerged paths:
#   (use "git add <file>..." to mark resolution)
#
#	both modified:      Makefile

**Comment by spco** [comment]
What is most useful here (sorry, it would be more useful if I could see your screen!) would be if you can show me the output of 
git log --oneline --branches --graph
The top 15 lines or so would be useful, so I can see the topology of your local repository. That should give me enough information to know whether we can force-push safely.

**Comment by rs028** [comment]
I realize it is difficult to do it this way. Thanks for your patience.
This is the output:

* 0ddeb97 Rename modelConfigFunctions.f90 and temperature.f90
* 7107f8b Move atmosphere() and zenith() to temperature.f90, delete modelConfiguration/extraOutputSubroutines.f90
* 6f1a9d2 Move ro2Sum() to outputFunctions.f90
| * b32c2df Add osx as os option to .travis.yml.
| * 336e04e typo
| * 60588f3 Impose a sensible system for numbering input and output units. Add iso_fortran_env to atchem.f90 to allow us to use stderr rather than unit 6.
| * 70ba78c Rename tools/fTFMC.py to tools/mech_converter.py.
| * 7d9a906 Rename tools/{run_atchem.py -> setup_atchem.py}.
| * db914ac Add source files as prerequisites to make all. Remove OBJS as they are unused.
| * 127cf70 Add travis.
| * 6c2b45a Add tools/build.sh to build the executable, and change tools/run_atchem.py to fit this flow.
| * 8cbf530 Make tools/fTFMC.py more robust in where it is called from, and where the input file is.
|/  
* 65ed53d Fix spelling
* 063faca tools/fTFMC.py now uses absolute and relative paths correctly, ensuring it can be run from anywhere and called on any suitable file.
* 0220deb Replace LongReal_Kind with DOUBLE PRECISION. Also make a couple of variables lower-case.

**Comment by spco** [comment]
Ok, that's great. To clarify, this shows that in your local repository you have a branch coming off at 'Fix spelling' which contains the top three commits, while the 9 to the right are on the master branch.

This is great, and was what I was hoping for!

git push --force origin master

should fix your setup on GitHub. Let me know when that's done and I'll check whether that looks like it's worked.

**Comment by rs028** [comment]
Done. I think it's okay.
git status tells me I have unmerged paths, which I suppose refers to the conflict in Makefile.
So I will fix that (in its own branch) and commit and this time hopefully I won't mess up. Right?

**Comment by spco** [comment]
I expect so. However, the fix of the merge conflict has to be done in that same branch, since we cannot merge that branch until it's fixed.

**Comment by rs028** [comment]
I think I fixed the conflict in Makefile. But I can't find the conflict in modelConfigFunctions.f90 (I di not change that file only renamed it), so I will leave it as is, for the moment.

**Comment by spco** [comment]
Hi Roberto, I'm back!

I'm looking to fix this merge conflict, but there's still a few issues remaining. Can you tell me whether the 'allow maintainers to make edits' checkbox (towards the bottom of the right-hand side menu on this page) is ticked?

I think I'm going to need you to fix the merge conflicts at your end. First of all, it's best to ensure your master branch is correctly up to date with the upstream:
First of all, make sure you haven't got any local modifications you want to save, that aren't in the GitHub repo. On `master` branch,
`git reset --hard b32c2dfc`
`git push --force`
`git pull upstream origin`
`git push origin`
That should then mean your local repo and your GitHub repo both have the correct master branch, up to date with mine.
Once that is done, try to fix the merge conflicts locally, then push to the PR in the usual way. Ideally, you should rebase the branch onto the head of master, by which I mean move the branch so it attaches to the top of the master branch rather than halfway down as it currently does. This can be done by:
`git checkout reorganize`
`git rebase master`
This will likely cause some (probably the same) conflicts, but these will be easier to fix locally. Once you're happy that these are fixed, 
`git push` (you may need `git push --force` if it complains)
should give us what we need. Let me know how you get on.

**Comment by rs028** [comment]
Hi Sam, welcome back.
the 'Allow edits from maintainers'  checkbox is ticked.

I am getting an error when doing ` git pull upstream origin` : fatal: Couldn't find remote ref origin
Should it be `git pull upstream master`?

**Comment by spco** [comment]
Ah, of course, yes it should be!

**Comment by rs028** [comment]
I keep messing this up. I am going to close this PR and delete the branch and start over with a new branch, it is easier.
Once I have committed everything in the new branch should I merge (or rebase?) with master and then push to my remote or should I just push to my remote from the new branch?

**Comment by spco** [comment]
That might be easier at this stage, although we shouldn't in general have to do this. I'll figure out the specifics of why this won't merge nicely.

Make sure your new branch is based on the head of master, and then you should just push to the origin from the new branch when the branch is complete or has at least one commit on it.

**Pull request closed without merging**
