### PR TITLE
Test scenarios

### PR DESCRIPTION
**Pull request by rs028**
This branch contains a reorganization of the test scenarios. As discussed in #47 the `short` and `single_reac_of_interest` tests have been merged, and given more sensible parameters.
The test `short_extended` has been converted into `short_ext1` , `short_ext2` , `short_ext3` , `short_ext4` to verify the calculations and conversions of environment variables H2O, RH, M, DEC, ROOFOPEN.

The other tests `spec_*` will need tweaking, but probably better in a separate PO (lots of files!)

### CODE REVIEW

**Comment by rs028** [comment]
NB: short_ext2  and short_ext3 give different results for DEC. Need to investigate before merging.

**Comment by spco** [comment]
This looks good - I'm just going to interject to say don't do anything to the `spec_*` tests, as you mentioned above, as I'm also working on tweaking one of those anyway (to get the JFac stuff working - the tests are currently being a pain because OSX and Linux are giving different values). Definitely better to do those after I've done mine, and definitely in a separate PR too - this one is very much pushing what's acceptable in size!

**Comment by rs028** [comment]
Okay. I will finish this and then pass it on to you. I can't verify why it fails the tests on macos, though,

**Comment by spco** [comment]
Ok. I need to do more work on understanding why Linux and macOS are behaving differently - the test in #203 is also giving different results, as does #128 which still has never been merged. Once I understand that, we can proceed with merging this.

**Comment by spco** [comment]
@rs028 , can I ask whether the stoichiometric coefficient will ever be anything other than 1? This is currently hard-coded to 1 in `readReactions()` (`clcoeff` and `crcoeff` are the two variables that hold this). Is it ever likely to be anything other than 1? If not, my investigations are showing that I might do well to remove it to improve the macOS/linux difficulty. I'll need to investigate further, but Id like to know whether it _could_ be stripped out or whether that is not acceptable.

**Comment by spco** [comment]
To add to the above, it seems that removing the stoichiometric coefficient doesn't make much of a difference to the numerical stability anyway, so my question is neither here nor there (although if it really won't be anything other than 1 then let's remove it!). I've discovered where the algorithm is going wrong, and it's a bit of a pain - it's numerical stability of subtraction of very similar numbers. I'll have to look into whether I can force it to be more robust. Otherwise, it might be enough to change the underlying .fac file in some way to sidestep the issue in the tests.

**Comment by rs028** [comment]
I am not sure, to be honest. If it does not create a problem, then I would say to keep the stoichiometric coefficient, just in case.

Can you elaborate on the issue with the fac file?

**Comment by spco** [comment]
Ok, we'll leave it for now, as it doesn't make a difference.

The issue (I'm still investigating to understand this further) seems to be an issue of numerical stability. Deep within the resid() function, we hit a line that essentially does the calculation a = -2.990519116362E+07 + 2.990519116361E+07. This is a well-known issue with subtraction in finite precision calculations - the difference between these two is minute relative to their size, and so the precision of the resulting number is affected, because the finite representation loses digits of accuracy.

It seems like this is the cause of the difference we see - linux and macOS are treating this very slightly differently, but then this difference gets multiplied over successive iterations (we're doing several thousand iterations so this quickly balloons).

The usual way to treat this is to rearrange the equation to avoid losing precision. I need to spend a bit of time seeing whether this is possible. Otherwise, it may be the case that this situation is in fact incredibly rare but we're unlucky to have hit it due to the numbers in our .fac file - perhaps changing one a little will be enough to avoid losing precision. The former option is preferable, since it would improve the code, but I need to see further how it plays out to see whether that's possible.

**Comment by rs028** [comment]
I see. I will leave that to you then :)

**Comment by spco** [comment]
I've just had to tweak the DEC value in `short_ext3` to give a stable value. This instability across platforms is a real pain, but I can't look at it right now.

**Comment by rs028** [comment]
@spco All right. Good job. How serious do you think this instability issue is? I mean can we trust the results on a given platform?

**Comment by spco** [comment]
We need to have a chat about this, as I think it is going to require further attention. I've not seen significant differences in the overall simulation outcomes in the tests we've run, it's usually just a case that it takes a different number of iterations, and outputs slightly perturbed values.

That said, it is a worry, especially as I don't have a firm grasp on when this might actually have a large effect on the overall outcome.

Changing to use openlbim has helped, but we still get varying results, and enough to worry me. I think it's probably linked to the conditioning of the system - we're handling some number of the size 1e15, and some of size 1e-30 - that is never a good situation to be in finite precision arithmetic, and so it will need more work to make this algorithm more robust. A very good starting point would be to work out where and when it issues IEEE underflow warnings, as that's a signal that precision is definitely being lost.

Can we talk in person about this sometime soon? Perhaps tomorrow?

**Comment by rs028** [comment]
Yes, I am in all day tomorrow. Just send me an invite for a time that is good for you.

**Pull request merged**
