### PR TITLE
Add LICENSE.md, and a license header to each source file.

### PR DESCRIPTION
**Pull request by spco**

### CODE REVIEW

**Comment by spco** [comment]
Addresses #243 and #246. These can both be closed when this merges. 

@rs028 Let me know if this looks OK to you - I have added copyright for you just you and I to all of the testsuite stuff, as that is all brand new.

**Comment by spco** [comment]
This is ready for merge if you are happy with it @rs028 . The only remaining step is to rename it to AtChem2 or similar, and release the version.

**Comment by rs028** [comment]
@spco, okay let's do the final merge! for the name I'd keep it simple. How about `Atchem+`?

**Comment by spco** [comment]
My only issue with that is that GitHub doesn't allow `+` as a character in the repository name, so it would come out as `Atchem-`

**Comment by rs028** [comment]
AtChemX?

**Comment by rs028** [comment]
or back to the original idea of AtChem2?

**Comment by spco** [comment]
Either of those sound good - your choice!

**Comment by rs028** [comment]
Okay, let's go with AtChem2. Not very imaginative, maybe, but easy and clear.

**Comment by spco** [comment]
Ok, sounds good. I think the simplicity is the most important part. I will do that tomorrow. If we change the repo name to match that (probably best long-term) there may be a little work to tweak your local repo as well, but we can sort that out.

**Comment by rs028** [comment]
All right. I don't mind if I have to delete my repo and fork again. If it makes things simpler.

**Pull request merged**
